services:
  postgres:
    image: postgres:latest
    container_name: game-event-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5430:5432"
    restart: unless-stopped
    networks:
      - game-event-service-network
  
  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - game-event-service-network
  
  kafka:
    image: wurstmeister/kafka:latest
    restart: unless-stopped
    environment:
      KAFKA_LOG_DIRS: /kafka-data
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://127.0.0.1:8001,INTERNAL://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CREATE_TOPICS: >
        game_status:1:1,
        schedule_game:1:1,
    depends_on:
      - zookeeper
    networks:
      - game-event-service-network
    volumes:
      - game-event-service-kafka-data:/kafka-data
    ports:
      - '8001:9092'

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - kafka
    networks:
      - game-event-service-network
    ports:
      - "8003:8080"
    volumes:
      - D:/dnd/GameEventsMicroservice/src/Presentation/GameEventMicroservice.Presentation.Kafka/protos:/schemas
    environment:
      kafka.clusters.0.name: kafka
      kafka.clusters.0.bootstrapServers: kafka:9094
      kafka.clusters.0.defaultKeySerde: ProtobufFile
      kafka.clusters.0.defaultValueSerde: ProtobufFile
      
      kafka.clusters.0.serde.0.name: ProtobufFile
      kafka.clusters.0.serde.0.properties.protobufFilesDir: /schemas/
      
      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.game_status: dnd.GameStatusKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.schedule_game: dnd.GameScheduleKey
      
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.game_status: dnd.GameStatusValue
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.schedule_game: dnd.GameScheduleValue

networks:
  game-event-service-network:
    driver: bridge

volumes:
  game-event-service-kafka-data: